axis_linear: 
  x: 1  # Left thumb stick vertical
  y: 0  # left thumb stick horizontal
  z: 7  # D pad vertical
scale_linear:
  x: 0.5
  y: 0.5
  z: -0.1
scale_linear_turbo:
  x: 5.0
  y: 5.0
  z: -0.5

axis_angular: 
  pitch: 4 # right thumb stick vertical
  yaw: 3 # right thumb stick horizontal
  roll: 6 # D pad horizontal
scale_angular:
  pitch: 1.5
  yaw: 1.5
  roll: -1.5
scale_angular_turbo:
  pitch: 3.0
  yaw: 3.0
  roll: -3.0

enable_button: 4 # Left bumper
enable_turbo_button: 5  # Right bumper