defaults:
  - model@tsgrasp_model: tsgraspnet
  - model@ctn_model: temporal_ctn
  - training: default
  - data: acronymvid
  - _self_

ctn_ckpt: /home/playert/Research/tsgrasp/ckpts/ctn_11_17/model.ckpt
tsgrasp_ckpt: /home/playert/Research/tsgrasp/ckpts/tsgraspnet_11_17/model.ckpt
# tsgrasp_ckpt: /home/playert/Research/tsgrasp/ckpts/45000_1/model.ckpt

training:
  gpus: 0
  batch_size: 1

data:
  data_cfg:
    points_per_frame: 45000